<?php
// Load features.
include_once('ddk_job.features.inc');

/**
 * @file
 * Drupal core hook implementations.
 */

/**
 * Implementation of hook_form_alter().
 */
function ddk_job_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'job_node_form') {
    if (isset($form['locations'])) {
      // Use our own version of the location element.
      $form['locations']['#after_build'][] = 'ddk_job_location_field_alter';
    }
  }
}

/**
* Alter the location form field.
*/
function ddk_job_location_field_alter($form_element, &$form_state) {
  // Remmove the delete location checkbox if available.
  unset($form_element[0]['delete_location']);
  $form_element[0]['#title'] = t('Company');
  if (isset($form_element[0]['name'])) {
    $form_element[0]['name']['#title'] = t('Company name');
  }
  return $form_element;
}